=== janvejvoda92/semestralka/hra_save_jan_vejvoda.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element type="save_hry" name="save_hry"/>

    <xs:complexType name="save_hry">
        <xs:sequence>
            <xs:element type="hra" name="hra" maxOccurs="unbounded" minOccurs="0">
            </xs:element>
        </xs:sequence>
    </xs:complexType>    
    <xs:complexType name="hra">
        <xs:sequence>
            <xs:element type="o_savu" name="o_savu"/>
            <xs:element type="nastaveni_hry" name="nastaveni_hry"/>
            <xs:element type="postava" name="postava"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="jazyk" use="optional"/>
    </xs:complexType>  
    <xs:complexType name="o_savu">
        <xs:sequence>
            <xs:element type="xs:integer" name="id"/>
            <xs:element name="jmeno_postavy">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name= "agrese">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="pratelsky" />
                                        <xs:enumeration value="zly" />
                                        <xs:enumeration value="agresivni" />
                                        <xs:enumeration value="vzneÅ¡eny" />
                                        <xs:enumeration value="neutralni" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:attribute>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>  
            </xs:element>
            <xs:element name="rasa">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name= "schopnost">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="zvyseni_many" />
                                        <xs:enumeration value="zvyseni_zdravi" />
                                        <xs:enumeration value="ovladani_zvirat" />
                                        <xs:enumeration value="odolnost_proti_magii" />
                                        <xs:enumeration value="odolnost_vuci_nemocem" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:attribute>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="uroven">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:integer">
                            <xs:attribute name= "titul">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="zacatecnik" />
                                        <xs:enumeration value="novic" />
                                        <xs:enumeration value="ucen" />
                                        <xs:enumeration value="znalec" />
                                        <xs:enumeration value="mistr" />
                                        <xs:enumeration value="velmistr" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:attribute>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element type="datum_ulozeni" name="datum_ulozeni"/>
        </xs:sequence>
    </xs:complexType> 
    <xs:complexType name="datum_ulozeni">
        <xs:sequence>
            <xs:element type="xs:date" name="datum"/>
            <xs:element type="xs:time" name="cas"/>
        </xs:sequence>
    </xs:complexType> 
    <xs:complexType name="nastaveni_hry">
        <xs:sequence>
            <xs:element type="xs:string" name="obtiznost"/>
            <xs:element type="grafika" name="grafika"/>
            <xs:element type="zobrazeni" name="zobrazeni"/>
            <xs:element type="hudba" name="hudba"/>
            <xs:element type="ovladani" name="ovladani"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="grafika">
        <xs:sequence>
            <xs:element name="rozliseni">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="1920x1080"/>
                        <xs:enumeration value="1600x900"/>
                        <xs:enumeration value="1360x768"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="xs:integer" name="jas"/>
            <xs:element type="xs:string" name="detail_krajiny"/>
            <xs:element name="odraz_vody">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="ano|ne"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="xs:string" name="kvalita_odrazu_vody"/>
            <xs:element type="xs:integer" name="dohled"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="zobrazeni">
        <xs:sequence>
            <xs:element type="xs:string" name="mnozstvi_ktve"/>
            <xs:element name="kompas">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="ano|ne"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="navigacni_kriz">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="ano|ne"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="mini_mapa">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="ano|ne"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="titulky">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="ano|ne"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="hudba">
        <xs:sequence>
            <xs:element type="xs:integer" name="zvuky_uroven"/>
            <xs:element type="xs:integer" name="hudba_uroven"/>
            <xs:element type="xs:integer" name="hlas_uroven"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ovladani">
        <xs:sequence>
            <xs:element type="xs:string" name="mys"/>
            <xs:element type="xs:string" name="citlivost_mysi"/>
            <xs:element name="klavesnice">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="qwertz|qwerty"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="postava">
        <xs:sequence>
            <xs:element type="info_o_postave" name="info_o_postave"/>
            <xs:element type="data_postava" name="data_postava"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="info_o_postave">
        <xs:sequence>
            <xs:element type="sily_postavy" name="sily_postavy"/>
            <xs:element type="vyzbroj" name="vyzbroj"/>
            <xs:element type="sperky" name="sperky"/>
            <xs:element type="vyzbrojeni" name="vyzbrojeni"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="sily_postavy">
        <xs:sequence>
            <xs:element type="xs:integer" name="zdravy_ak"/>  
            <xs:element  name="zdravy_cel">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:integer">
                            <xs:attribute type="xs:decimal" name= "obnova_zdravy"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element type="xs:integer" name="mana_ak"/>
            <xs:element name="mana_cel">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:integer">
                            <xs:attribute type="xs:decimal" name= "obnova_many"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element type="xs:integer" name="vydrz_ak"/>
            <xs:element name="vydrz_cel">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:integer">
                            <xs:attribute type="xs:decimal" name= "obnova_vydrze"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="vyzbroj">
        <xs:sequence>
            <xs:element type="xs:string" name="hlava"/>
            <xs:element name="hrudnik">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name= "odev_pod_zbroji">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="saty" />
                                        <xs:enumeration value="kozene_saty" />
                                        <xs:enumeration value="nic" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:attribute>
                            <xs:attribute name= "vylepseni" type="xs:string" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element type="xs:string" name="ruce"/>
            <xs:element name="boty">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name= "vyska_bot">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                       <xs:pattern value="nizke|vysoke"/> 
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:attribute>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="sperky">
        <xs:sequence>
            <xs:element type="xs:string" name="krk"/>
            <xs:element type="xs:string" name="ruce"/>
            <xs:element type="xs:string" name="hlava"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="vyzbrojeni">
        <xs:sequence>
            <xs:element type="xs:string" name="prava_ruka"/>
            <xs:element type="xs:string" name="leva_ruka"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="data_postava">
        <xs:sequence>
            <xs:element type="xs:string" name="mince"/>
            <xs:element name="titul">
                 <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name= "postaveni"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element type="xs:string" name="povolani"/>
            <xs:element name="aktivni_ukol">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name= "faze_ukolu"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="frakce">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="kralovstvi"/>
                        <xs:enumeration value="neutralni"/>
                        <xs:enumeration value="cisarstvi"/>
                        <xs:enumeration value="svoborni_obyvatele"/>
                        <xs:enumeration value="kralove_zeme"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="hledany">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="ano|ne"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="xs:string" name="lokace"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== janvejvoda92/semestralka/newXMLDocument.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?xml-stylesheet type="text/xsl" href="transformace.xsl"?>
<save_hry xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="hra_save_jan_vejvoda.xsd">
    <!--save 1-->
    <hra jazyk="CS">
        <o_savu>
            <id>1</id>
            <jmeno_postavy agrese="agresivni">Nicitel</jmeno_postavy>
            <rasa schopnost="zvyseni_many">Svěetlý Elf</rasa>
            <uroven titul="novic">19</uroven>
            <datum_ulozeni>
                <datum>2006-11-23</datum>
                <cas>15:46:45</cas>
            </datum_ulozeni>
        </o_savu>
        <nastaveni_hry>
            <obtiznost>znalec</obtiznost>
            <grafika>
                <rozliseni>1920x1080</rozliseni>
                <jas>6</jas>
                <detail_krajiny>ultra</detail_krajiny>
                <odraz_vody>ano</odraz_vody>
                <kvalita_odrazu_vody>stredni</kvalita_odrazu_vody>
                <dohled>20</dohled>
            </grafika>
            <zobrazeni>
                <mnozstvi_ktve>velke</mnozstvi_ktve>
                <kompas>ne</kompas>
                <navigacni_kriz>ano</navigacni_kriz>
                <mini_mapa>ano</mini_mapa>
                <titulky>ano</titulky>
            </zobrazeni>
            <hudba>
                <zvuky_uroven>15</zvuky_uroven>
                <hudba_uroven>10</hudba_uroven>
                <hlas_uroven>17</hlas_uroven>
            </hudba>
            <ovladani>
                <mys>pravak</mys>
                <citlivost_mysi>stredni</citlivost_mysi>
                <klavesnice>qwertz</klavesnice>
                
            </ovladani>
        </nastaveni_hry>
        <postava>
            <info_o_postave>
                <sily_postavy>
                    <zdravy_ak>150</zdravy_ak>
                    <zdravy_cel obnova_zdravy="1.0">320</zdravy_cel>
                    <mana_ak>200</mana_ak>
                    <mana_cel obnova_many="1.0">200</mana_cel>
                    <vydrz_ak>180</vydrz_ak>
                    <vydrz_cel obnova_vydrze="1.0">200</vydrz_cel>
                </sily_postavy>
                <vyzbroj>
                    <hlava>Lehka Elfi helma</hlava>
                    <hrudnik odev_pod_zbroji="saty" vylepseni="vylepsena">Elfska zbroj</hrudnik>
                    <ruce>Kozene rukavice</ruce>
                    <boty vyska_bot="vysoke">Kozene boty</boty>
                </vyzbroj>
                <sperky>
                    <krk>zlaty_privesek</krk>
                    <ruce>stribrny_prsten</ruce>
                    <hlava>N/</hlava>
                </sperky>
                <vyzbrojeni>
                    <prava_ruka>kratky_mec</prava_ruka>
                    <leva_ruka>ocelova_dyka</leva_ruka>
                </vyzbrojeni>
            </info_o_postave>
            <data_postava>
                <mince>682 zlatych</mince>
                <titul postaveni="vazeny">n/</titul>
                <povolani>kupec</povolani>
                <aktivni_ukol faze_ukolu="2">prodej cenný predmet</aktivni_ukol>
                <frakce>kralovstvi</frakce>
                <hledany>ne</hledany>
                <lokace>penvost zlomeného kamene</lokace>
            </data_postava>
        </postava>
    </hra>
    <!--save 2-->
    <hra jazyk="CS">
        <o_savu>
            <id>2</id>
            <jmeno_postavy agrese="agresivni">stín</jmeno_postavy>
            <rasa schopnost="zvyseni_many">tmný Elf</rasa>
            <uroven titul="novic">23</uroven>
            <datum_ulozeni>
                <datum>2005-04-16</datum>
                <cas>10:12:12</cas>
            </datum_ulozeni>
        </o_savu>
        <nastaveni_hry>
            <obtiznost>zacatecnik</obtiznost>
            <grafika>
                <rozliseni>1920x1080</rozliseni>
                <jas>6</jas>
                <detail_krajiny>stredni</detail_krajiny>
                <odraz_vody>ne</odraz_vody>
                <kvalita_odrazu_vody>n/</kvalita_odrazu_vody>
                <dohled>12</dohled>
            </grafika>
            <zobrazeni>
                <mnozstvi_ktve>zadne</mnozstvi_ktve>
                <kompas>ano</kompas>
                <navigacni_kriz>ano</navigacni_kriz>
                <mini_mapa>ne</mini_mapa>
                <titulky>ne</titulky>
            </zobrazeni>
            <hudba>
                <zvuky_uroven>10</zvuky_uroven>
                <hudba_uroven>0</hudba_uroven>
                <hlas_uroven>20</hlas_uroven>
            </hudba>
            <ovladani>
                <mys>levak</mys>
                <citlivost_mysi>nizka</citlivost_mysi>
                <klavesnice>qwerty</klavesnice>  
            </ovladani>
        </nastaveni_hry>
        <postava>
            <info_o_postave>
                <sily_postavy>
                    <zdravy_ak>200</zdravy_ak>
                    <zdravy_cel obnova_zdravy="1.0">250</zdravy_cel>
                    <mana_ak>180</mana_ak>
                    <mana_cel obnova_many="1.0">300</mana_cel>
                    <vydrz_ak>200</vydrz_ak>
                    <vydrz_cel obnova_vydrze="1.0">200</vydrz_cel>
                </sily_postavy>
                <vyzbroj>
                    <hlava>n/</hlava>
                    <hrudnik odev_pod_zbroji="saty" vylepseni="zakladni">Elfská zbroj</hrudnik>
                    <ruce>citlivé rukavice</ruce>
                    <boty vyska_bot="nizke">plátěné boty</boty>
                </vyzbroj>
                <sperky>
                    <krk>přívěšek</krk>
                    <ruce>zlatý prsten</ruce>
                    <hlava>čelenka</hlava>
                </sperky>
                <vyzbrojeni>
                    <prava_ruka>dlouhý nůž</prava_ruka>
                    <leva_ruka>dlouhý nůž černý</leva_ruka>
                </vyzbrojeni>
            </info_o_postave>
            <data_postava>
                <mince>700 zlatých</mince>
                <titul postaveni="vazeny">král zlodějů</titul>
                <povolani>zloděj</povolani>
                <aktivni_ukol faze_ukolu="6">špehování</aktivni_ukol>
                <frakce>neutralni</frakce>
                <hledany>ano</hledany>
                <lokace>předměstí zářivé slzy</lokace>
            </data_postava>
        </postava>
    </hra>
    <!--save 3-->
    <hra jazyk="CS">
        <o_savu>
            <id>3</id>
            <jmeno_postavy agrese="pratelsky">vítr</jmeno_postavy>
            <rasa schopnost="zvyseni_zdravi">člověk</rasa>
            <uroven titul="zacatecnik">12</uroven>
            <datum_ulozeni>
                <datum>2007-08-03</datum>
                <cas>23:32:01</cas>
            </datum_ulozeni>
        </o_savu>
        <nastaveni_hry>
            <obtiznost>mistr</obtiznost>
            <grafika>
                <rozliseni>1360x768</rozliseni>
                <jas>12</jas>
                <detail_krajiny>vysoke</detail_krajiny>
                <odraz_vody>ano</odraz_vody>
                <kvalita_odrazu_vody>stredni</kvalita_odrazu_vody>
                <dohled>10</dohled>
            </grafika>
            <zobrazeni>
                <mnozstvi_ktve>male</mnozstvi_ktve>
                <kompas>ne</kompas>
                <navigacni_kriz>ano</navigacni_kriz>
                <mini_mapa>ne</mini_mapa>
                <titulky>ano</titulky>
            </zobrazeni>
            <hudba>
                <zvuky_uroven>20</zvuky_uroven>
                <hudba_uroven>5</hudba_uroven>
                <hlas_uroven>15</hlas_uroven>
            </hudba>
            <ovladani>
                <mys>pravak</mys>
                <citlivost_mysi>vysoka</citlivost_mysi>
                <klavesnice>qwerty</klavesnice>  
            </ovladani>
        </nastaveni_hry>
        <postava>
            <info_o_postave>
                <sily_postavy>
                    <zdravy_ak>350</zdravy_ak>
                    <zdravy_cel obnova_zdravy="1.3">250</zdravy_cel>
                    <mana_ak>180</mana_ak>
                    <mana_cel obnova_many="1.0">100</mana_cel>
                    <vydrz_ak>200</vydrz_ak>
                    <vydrz_cel obnova_vydrze="0.8">250</vydrz_cel>
                </sily_postavy>
                <vyzbroj>
                    <hlava>n/</hlava>
                    <hrudnik odev_pod_zbroji="saty" vylepseni="vylepsena">kožená zbroj</hrudnik>
                    <ruce>kozene rukavice</ruce>
                    <boty vyska_bot="vysoke">kozene boty</boty>
                </vyzbroj>
                <sperky>
                    <krk>kozeny nahrdelnik</krk>
                    <ruce>prsten</ruce>
                    <hlava>nic</hlava>
                </sperky>
                <vyzbrojeni>
                    <prava_ruka>luk</prava_ruka>
                    <leva_ruka>luk</leva_ruka>
                </vyzbrojeni>
            </info_o_postave>
            <data_postava>
                <mince>100 zlatých</mince>
                <titul postaveni="neb_postaveni"></titul>
                <povolani>učeň</povolani>
                <aktivni_ukol faze_ukolu="2">pomoc mistovy</aktivni_ukol>
                <frakce>neutralni</frakce>
                <hledany>ne</hledany>
                <lokace>temný_les</lokace>
            </data_postava>
        </postava>
    </hra>
    <!--save 4-->
    <hra jazyk="CS">
        <o_savu>
            <id>4</id>
            <jmeno_postavy agrese="vznešeny">světlo</jmeno_postavy>
            <rasa schopnost="zvyseni_many">člověk</rasa>
            <uroven titul="znalec">34</uroven>
            <datum_ulozeni>
                <datum>2007-04-20</datum>
                <cas>14:56:02</cas>
            </datum_ulozeni>
        </o_savu>
        <nastaveni_hry>
            <obtiznost>mistr</obtiznost>
            <grafika>
